import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { createInitialState } from '../src/marathon/model.js';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const url = process.env.MARATHON_TEST_URL || 'http://127.0.0.1:5180/THE-DIVINE-SHOW/';
const output = process.env.MARATHON_TEST_OUTPUT || join(import.meta.dirname, '../test-output');
await mkdir(output, { recursive: true });
const owner = { uid: 'test-owner', email: 'owner@example.test' };
const oldPath = 'users/test-owner/trackers/marathon120-v9';
const newPath = 'users/test-owner/trackers/marathon-current-v11';
const cloud = new Map([[oldPath, { state: createInitialState('2026-08-30', '2026-08-30T08:00:00Z') }]]);
let offline = false;
let writes = 0;
const browser = await chromium.launch({ headless: true });

const firestoreStub = `
const subscribers = new Set();
const request = async (body) => {
  const response = await fetch('/__test__/cloud', { method: 'POST', body: JSON.stringify(body) });
  if (!response.ok) throw new Error('Test offline');
  return response.json();
};
const snapshot = (data) => ({ exists: () => data !== null, data: () => data || undefined, metadata: { fromCache: false, hasPendingWrites: false } });
export const doc = (_db, ...parts) => parts.join('/');
export const serverTimestamp = () => new Date().toISOString();
export const setDoc = async (path, value, options) => request({ type: 'write', operations: [{ type: 'set', path, value, merge: options?.merge }] });
export const onSnapshot = (path, _options, callback, onError) => {
  const item = { path, callback }; subscribers.add(item);
  request({ type: 'get', path }).then((value) => { if(subscribers.has(item)) callback(snapshot(value)); }).catch(onError);
  return () => subscribers.delete(item);
};
export const runTransaction = async (_db, callback) => {
  const operations = [];
  const result = await callback({
    get: async (path) => snapshot(await request({ type: 'get', path })),
    set: (path, value, options) => operations.push({ type: 'set', path, value, merge: options?.merge }),
    delete: (path) => operations.push({ type: 'delete', path }),
  });
  if (operations.length) await request({ type: 'write', operations });
  for(const item of subscribers) item.callback(snapshot(await request({ type: 'get', path: item.path })));
  return result;
};`;

async function setup(context, user = owner) {
  // Substitute only the configured account fingerprint, using a synthetic test identity.
  await context.route('**/src/marathon/accountStorage.js*', async (route) => {
    const response = await route.fetch();
    const fingerprint = createHash('sha256').update(owner.email).digest('hex');
    const body = (await response.text()).replace(/const REQUESTED_ACCOUNT_HASH = ["'][a-f0-9]+["']/, `const REQUESTED_ACCOUNT_HASH = '${fingerprint}'`);
    return route.fulfill({ response, body });
  });
  await context.route('**/src/auth/roles.js*', async (route) => {
    const response = await route.fetch();
    const body = (await response.text()).replace(/export const ADMIN_UID = ["'][^"']+["']/, `export const ADMIN_UID = '${owner.uid}'`);
    return route.fulfill({ response, body });
  });
  await context.route('**/src/firebase.js*', (route) => route.fulfill({ contentType: 'text/javascript', body: 'export const auth={}; export const db={}; export const storage={}; export const firebaseConfigured=true; export const googleProvider={};' }));
  await context.route(/\/firebase_auth\.js(\?|$)/, (route) => route.fulfill({ contentType: 'text/javascript', body: `export const onAuthStateChanged=(_auth,cb)=>{queueMicrotask(()=>cb(${JSON.stringify(user)}));return ()=>{}}; export const signOut=async()=>{}; export const signInWithPopup=async()=>{};` }));
  await context.route(/\/firebase_firestore\.js(\?|$)/, (route) => route.fulfill({ contentType: 'text/javascript', body: firestoreStub }));
  await context.route('**/__test__/cloud', async (route) => {
    if (offline) return route.fulfill({ status: 503, body: '{}' });
    const request = route.request().postDataJSON();
    if (request.type === 'get') return route.fulfill({ contentType: 'application/json', body: JSON.stringify(cloud.get(request.path) || null) });
    for (const op of request.operations) {
      if (op.type === 'delete') cloud.delete(op.path);
      else { cloud.set(op.path, op.merge ? { ...cloud.get(op.path), ...op.value } : op.value); if (op.path.includes('/trackers/')) writes++; }
    }
    return route.fulfill({ contentType: 'application/json', body: '{}' });
  });
}

async function checkWidth(page, name) {
  const measure = await page.evaluate(() => ({ viewport: document.documentElement.clientWidth, content: document.documentElement.scrollWidth }));
  assert.ok(measure.content <= measure.viewport + 1, `${name}: ${JSON.stringify(measure)}`);
}

try {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, timezoneId: 'Europe/Moscow' });
  await setup(context);
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('console', (message) => { if (message.type() === 'error' && !message.text().includes('503 (Service Unavailable)')) errors.push(message.text()); });
  await page.clock.install({ time: new Date('2026-09-06T10:00:00Z') });
  await page.goto(url);
  await page.getByRole('heading', { name: 'Мои аскезы', exact: true }).waitFor();
  assert.equal(cloud.has(oldPath), false, 'Old cloud history must be deleted for the owner');
  assert.equal(cloud.get(newPath).state, null, 'Reset must not auto-start');
  const startButton = page.getByRole('button', { name: 'Принимаю обязательства. Начать', exact: true });
  assert.equal(await startButton.isEnabled(), false);
  assert.equal(await page.getByRole('checkbox').count(), 6);
  await page.screenshot({ path: join(output, 'start-mobile.png'), fullPage: true });
  await checkWidth(page, 'mobile start');
  for (const checkbox of await page.getByRole('checkbox').all()) await checkbox.check();
  assert.equal(await startButton.isEnabled(), false, 'Purpose is required too');
  await page.getByLabel('Ради чего я прохожу эти 120 дней', { exact: false }).fill('Хочу действовать свободно и сохранять здоровье.');
  await startButton.click();
  await page.getByRole('button', { name: 'Да, начинаю', exact: true }).click();
  await page.getByText('Дни', { exact: true }).click();
  await page.getByRole('heading', { name: 'Все 120 дней перед глазами', exact: true }).waitFor();
  assert.equal(await page.locator('.day-tile').count(), 120);
  assert.equal(cloud.get(newPath).state.commitments.items.length, 6);
  const journeyId = cloud.get(newPath).state.journeyId;

  assert.equal(await page.getByText('Цели этого дня', { exact: true }).count(), 0, 'The old duplicate goal system must be gone');
  await page.getByTitle('Настроить Кодекс').click();
  const codexDialog = page.getByRole('dialog', { name: 'Настройка Кодекса' });
  await codexDialog.getByRole('button', { name: 'Новое правило', exact: true }).click();
  await codexDialog.getByLabel('Правило', { exact: true }).fill('Отжиматься каждый день');
  await codexDialog.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await codexDialog.getByTitle('Закрыть').click();
  await page.getByText('Отжиматься каждый день', { exact: true }).first().waitFor();
  await page.waitForTimeout(900);
  assert.ok(cloud.get(newPath).state.codexRules.some((rule) => rule.title === 'Отжиматься каждый день'));
  await page.getByRole('button', { name: 'Шаги', exact: true }).last().click();
  await page.getByRole('button', { name: 'Новый шаг', exact: true }).click();
  await page.getByRole('dialog', { name: 'Новый шаг' }).waitFor();
  await page.getByRole('dialog', { name: 'Новый шаг' }).getByTitle('Закрыть').click();
  await page.getByRole('button', { name: 'Сегодня', exact: true }).last().click();

  // The test tab is disconnected from its fake cloud, then immediately reloaded after typing.
  offline = true;
  await page.getByRole('spinbutton', { name: 'Вес, кг', exact: true }).fill('69.3');
  await page.reload();
  await page.getByRole('spinbutton', { name: 'Вес, кг', exact: true }).waitFor();
  assert.equal(await page.getByRole('spinbutton', { name: 'Вес, кг', exact: true }).inputValue(), '69.3');
  await page.getByText('Отжиматься каждый день', { exact: true }).waitFor();
  offline = false;
  await page.getByRole('button', { name: 'Повторить синхронизацию', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Калории', exact: true }).fill('1850');
  await page.getByRole('spinbutton', { name: 'Активные', exact: true }).fill('400');
  await page.getByRole('spinbutton', { name: 'Шаги', exact: true }).fill('9000');
  for (const yes of await page.locator('button[aria-label$=": да"]').all()) await yes.click();
  await page.getByText('Рефлексия дня', { exact: false }).click();
  await page.getByPlaceholder('Какой факт сегодня доказывает, что я двигаюсь?').fill('Сделал полезное действие и сохранил свой выбор.');
  await page.getByText('100 очков уже учтены.', { exact: false }).waitFor();
  assert.equal(await page.getByRole('spinbutton', { name: 'Калории', exact: true }).isEnabled(), true);
  await page.waitForFunction(() => document.querySelector('[aria-label="Сохранено в облаке"]'));
  await page.waitForTimeout(900);
  assert.equal(cloud.get(newPath).state.days[0].weight, '69.3');
  assert.equal(cloud.get(newPath).state.days[0].result, null, 'Today remains editable');
  assert.equal(cloud.get(newPath).state.days[0].calories, '1850');
  await checkWidth(page, 'mobile daily form');

  await page.clock.setSystemTime(new Date('2026-09-07T10:00:00Z'));
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await page.getByText('День 2 из 120', { exact: true }).waitFor();
  await page.getByText('Дни', { exact: true }).click();
  await page.getByRole('button', { name: '1 06.09', exact: true }).click();
  const adminDayDetails = page.getByRole('dialog', { name: 'День 1', exact: true });
  await adminDayDetails.waitFor();
  await adminDayDetails.getByText('Энергетический итог', { exact: true }).waitFor();
  await page.waitForTimeout(400);
  await adminDayDetails.screenshot({ path: join(output, 'day-details-admin-mobile.png') });
  await adminDayDetails.getByTitle('Закрыть').click();
  await page.getByText('Закрыт автоматически по сохранённым данным', { exact: false }).waitFor();
  assert.equal(await page.getByRole('spinbutton', { name: 'Калории', exact: true }).isEnabled(), false);
  await page.waitForTimeout(1000);
  assert.equal(cloud.get(newPath).state.days[0].result, 'strong');
  assert.equal(cloud.get(newPath).state.days[0].xp, 100);
  await page.screenshot({ path: join(output, 'automatic-mobile.png'), fullPage: true });
  await page.reload();
  await page.getByText('День 2 из 120', { exact: true }).waitFor();
  assert.equal(cloud.get(newPath).state.journeyId, journeyId);
  assert.equal(cloud.get(newPath).state.days[0].xp, 100);
  await page.getByRole('button', { name: 'Статистика', exact: true }).last().click();
  await page.getByRole('heading', { name: 'Что меняется по фактам', exact: true }).waitFor();
  await checkWidth(page, 'mobile statistics');
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.screenshot({ path: join(output, 'statistics-desktop.png'), fullPage: true });
  await checkWidth(page, 'desktop statistics');
  const beforeIdle = writes;
  await page.waitForTimeout(1600);
  assert.equal(writes, beforeIdle, 'Sync must settle without endless writes');
  await page.getByRole('button', { name: 'Курс', exact: true }).last().click();
  await page.getByRole('heading', { name: 'Кем я становлюсь', exact: true }).waitFor();
  await page.getByRole('heading', { name: 'Главные векторы', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Развитие', exact: true }).click();
  await page.getByRole('heading', { name: 'Дерево развития', exact: true }).waitFor();
  await page.getByText('Перенос в PROD', { exact: true }).first().waitFor();
  await page.getByRole('button', { name: 'Желания', exact: true }).click();
  await page.getByRole('heading', { name: 'Карта желаний', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Персонаж', exact: true }).click();
  await page.getByRole('heading', { name: /Персонаж · уровень/ }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: join(output, 'course-mobile.png'), fullPage: true });
  await checkWidth(page, 'mobile course');
  await page.setViewportSize({ width: 1440, height: 900 });
  await checkWidth(page, 'desktop course');
  await page.getByRole('button', { name: 'Шаги', exact: true }).last().click();
  await page.getByRole('heading', { name: 'Шаги, которые уже сделаны', exact: true }).waitFor();
  const stepsPath = 'users/test-owner/trackers/steps-v1';
  await page.getByRole('button', { name: 'Новый шаг', exact: true }).click();
  const stepDialog = page.getByRole('dialog', { name: 'Новый шаг' });
  await stepDialog.getByRole('textbox', { name: 'Название', exact: true }).fill('Высказаться на встрече');
  await stepDialog.getByRole('button', { name: /4.*Смело/ }).click();
  await stepDialog.getByRole('button', { name: 'Сохранить шаг', exact: true }).click();
  await page.locator('.steps-card').filter({ hasText: 'Высказаться на встрече' }).getByTitle('Взять на сегодня').click();
  await page.getByRole('heading', { name: 'Сегодня', exact: true }).waitFor();
  await page.locator('.steps-card').filter({ hasText: 'Высказаться на встрече' }).getByRole('button', { name: 'Выполнено', exact: true }).click();
  const completion = page.getByRole('dialog', { name: 'Шаг сделан' });
  await completion.getByRole('spinbutton', { name: 'До', exact: true }).fill('8');
  await completion.getByRole('spinbutton', { name: 'В процессе', exact: true }).fill('6');
  await completion.getByRole('spinbutton', { name: 'После', exact: true }).fill('3');
  await completion.getByRole('textbox', { name: 'Что произошло на самом деле?' }).fill('Ответили спокойно.');
  await completion.getByRole('button', { name: 'Засчитать действие · +4', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('[aria-label="Сохранено в облаке"]'));
  await page.waitForTimeout(900);
  assert.equal(cloud.get(stepsPath).state.executions.length, 1);
  assert.equal(cloud.get(stepsPath).state.executions[0].points, 4);
  await page.locator('.steps-card').filter({ hasText: 'Высказаться на встрече' }).getByRole('button', { name: 'Выполнено', exact: true }).click();
  await completion.getByRole('spinbutton', { name: 'До', exact: true }).fill('4');
  await completion.getByRole('spinbutton', { name: 'В процессе', exact: true }).fill('3');
  await completion.getByRole('spinbutton', { name: 'После', exact: true }).fill('1');
  await completion.getByRole('button', { name: 'Засчитать действие · +4', exact: true }).click();
  await page.getByRole('button', { name: 'Статистика', exact: true }).last().click();
  await page.getByRole('button', { name: 'Всё время', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('button[aria-pressed="true"]')?.textContent === 'Всё время');
  await page.getByText('Шаг сделан', { exact: true }).waitFor({ state: 'hidden' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: join(output, 'steps-mobile.png'), fullPage: true });
  await checkWidth(page, 'mobile steps statistics');
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: join(output, 'steps-desktop.png'), fullPage: true });
  await checkWidth(page, 'desktop steps statistics');
  await page.getByRole('button', { name: 'Карта шагов', exact: true }).click();
  await page.getByTitle('Управлять категориями').click();
  const categoriesDialog = page.getByRole('dialog', { name: 'Категории', exact: true });
  await categoriesDialog.getByPlaceholder('Новая категория').fill('Практика');
  await categoriesDialog.getByTitle('Добавить категорию').click();
  await categoriesDialog.getByRole('textbox', { name: 'Название категории Практика' }).waitFor();
  await categoriesDialog.getByTitle('Закрыть').click();
  const stepCard = page.locator('.steps-card').filter({ hasText: 'Высказаться на встрече' });
  await stepCard.getByTitle('Другие действия').click();
  await stepCard.getByRole('button', { name: 'Изменить', exact: true }).click();
  const editStep = page.getByRole('dialog', { name: 'Изменить шаг' });
  await editStep.getByRole('combobox', { name: 'Категория' }).selectOption({ label: 'Практика' });
  await editStep.getByRole('button', { name: /1.*Разминка/ }).click();
  await editStep.getByRole('button', { name: 'Сохранить шаг' }).click();
  await stepCard.getByRole('button', { name: 'Выполнено', exact: true }).click();
  await completion.getByRole('spinbutton', { name: 'До', exact: true }).fill('2');
  await completion.getByRole('spinbutton', { name: 'В процессе', exact: true }).fill('2');
  await completion.getByRole('spinbutton', { name: 'После', exact: true }).fill('1');
  await completion.getByRole('button', { name: 'Засчитать действие · +1' }).click();
  await page.waitForTimeout(900);
  assert.deepEqual(cloud.get(stepsPath).state.executions.map((item) => item.points), [4, 4, 1]);
  await stepCard.getByRole('button', { name: 'История', exact: true }).click();
  await page.getByRole('dialog', { name: 'Высказаться на встрече' }).getByText('Выполнено', { exact: true }).waitFor();
  await page.getByRole('dialog', { name: 'Высказаться на встрече' }).getByRole('button', { name: /8.*6.*3/ }).click();
  const correction = page.getByRole('dialog', { name: 'Исправить запись' });
  await correction.getByRole('spinbutton', { name: 'До', exact: true }).fill('6');
  await correction.getByRole('button', { name: 'Сохранить исправление' }).click();
  await page.waitForTimeout(900);
  assert.equal(cloud.get(stepsPath).state.executions[0].before, 6);
  await page.getByRole('dialog', { name: 'Высказаться на встрече' }).getByTitle('Закрыть').click();
  await page.getByTitle('Управлять категориями').click();
  await page.getByRole('dialog', { name: 'Категории' }).getByTitle('Удалить категорию Практика').click();
  await page.getByRole('dialog', { name: 'Удалить запись?' }).getByRole('button', { name: 'Удалить', exact: true }).click();
  await page.getByRole('dialog', { name: 'Категории' }).getByTitle('Закрыть').click();
  await page.getByRole('button', { name: 'Боссы', exact: true }).click();
  await page.getByRole('button', { name: 'Новый Босс', exact: true }).click();
  const bossDialog = page.getByRole('dialog', { name: 'Новый шаг' });
  await bossDialog.getByRole('textbox', { name: 'Название' }).fill('Выступить без подготовки');
  await bossDialog.getByRole('button', { name: 'Сохранить шаг' }).click();
  await page.getByRole('heading', { name: 'Выступить без подготовки' }).waitFor();
  await page.getByRole('button', { name: 'Выполнено · +12' }).click();
  await completion.getByRole('spinbutton', { name: 'До', exact: true }).fill('9');
  await completion.getByRole('spinbutton', { name: 'В процессе', exact: true }).fill('6');
  await completion.getByRole('spinbutton', { name: 'После', exact: true }).fill('4');
  await completion.getByRole('button', { name: 'Засчитать действие · +12' }).click();
  await page.getByText('Побеждённые Боссы · 1').waitFor();
  await page.getByRole('button', { name: 'Разгрузка', exact: true }).click();
  await page.getByRole('button', { name: 'Добавить дело' }).click();
  const taskDialog = page.getByRole('dialog', { name: 'Новое дело' });
  await taskDialog.getByRole('textbox', { name: 'Что нужно сделать?' }).fill('Разобрать документы');
  await taskDialog.getByRole('spinbutton', { name: 'Примерно минут' }).fill('80');
  await taskDialog.getByRole('spinbutton', { name: 'Примерно ₽' }).fill('500');
  await taskDialog.getByRole('button', { name: 'Сохранить дело' }).click();
  const taskCard = page.locator('.steps-card').filter({ hasText: 'Разобрать документы' });
  await taskCard.dragTo(page.locator('.steps-kanban > section').filter({ has: page.getByRole('heading', { name: 'Запланировано', exact: true }) }));
  await page.getByRole('combobox', { name: 'Статус: Разобрать документы' }).selectOption('done');
  await page.getByText('1 ч 20 мин', { exact: true }).waitFor();
  await page.getByText('500 ₽', { exact: true }).waitFor();
  await page.waitForTimeout(900);
  assert.equal(cloud.get(stepsPath).state.energyTasks[0].status, 'done');
  assert.equal(cloud.get(stepsPath).state.energyTasks[0].estimatedMinutes, 80);
  await page.reload();
  await page.getByRole('button', { name: 'Шаги', exact: true }).first().click();
  await page.getByText('3 выполнений', { exact: false }).waitFor();
  assert.equal(cloud.get(stepsPath).state.executions.length, 4, 'Repeat and Boss history must persist after reload');
  assert.deepEqual(errors, []);
  await context.close();

  const sameAccountContext = await browser.newContext({ viewport: { width: 390, height: 844 }, timezoneId: 'Europe/Moscow' });
  await setup(sameAccountContext, owner);
  const sameAccountPage = await sameAccountContext.newPage();
  await sameAccountPage.goto(url);
  await sameAccountPage.getByText('Дни', { exact: true }).click();
  await sameAccountPage.getByRole('heading', { name: 'Все 120 дней перед глазами', exact: true }).waitFor();
  await sameAccountPage.getByRole('button', { name: 'Шаги', exact: true }).last().click();
  await sameAccountPage.getByText('Высказаться на встрече', { exact: true }).first().waitFor();
  await sameAccountPage.getByText('3 выполнений', { exact: false }).waitFor();
  await sameAccountContext.close();

  const other = { uid: 'test-other', email: 'other@example.test' };
  const otherPath = 'users/test-other/trackers/marathon120-v9';
  const otherState = createInitialState('2026-09-06', '2026-09-06T08:00:00Z');
  cloud.set(otherPath, { state: otherState });
  const otherContext = await browser.newContext({ viewport: { width: 390, height: 844 }, timezoneId: 'Europe/Moscow' });
  await setup(otherContext, other);
  const otherPage = await otherContext.newPage();
  await otherPage.goto(url);
  await otherPage.getByRole('heading', { name: 'Сегодняшние доказательства', exact: true }).waitFor();
  await otherPage.getByRole('button', { name: /Карта марафона/ }).click();
  await otherPage.getByRole('button', { name: '1 06.09', exact: true }).click();
  const memberDayDetails = otherPage.getByRole('dialog', { name: 'День 1', exact: true });
  await memberDayDetails.waitFor();
  await memberDayDetails.getByText('Мой Кодекс', { exact: true }).waitFor();
  assert.equal(await memberDayDetails.getByText('Без алкоголя', { exact: true }).count(), 1, 'Member Codex must not duplicate rules');
  assert.equal(await memberDayDetails.getByText('Без World of Tanks', { exact: true }).count(), 0, 'Admin-only rules must not leak into member accounts');
  await otherPage.waitForTimeout(400);
  await memberDayDetails.screenshot({ path: join(output, 'day-details-member-mobile.png') });
  await memberDayDetails.getByTitle('Закрыть').click();
  assert.equal(cloud.get(otherPath).state.journeyId, otherState.journeyId);
  assert.equal(await otherPage.getByText('Высказаться на встрече', { exact: true }).count(), 0, 'Another account must not see owner steps');
  await otherPage.screenshot({ path: join(output, 'member-today.png'), fullPage: true });
  await checkWidth(otherPage, 'member mobile today');
  await otherPage.getByRole('button', { name: 'Профиль', exact: true }).last().click();
  await otherPage.getByRole('heading', { name: /other@example.test|Мой профиль/ }).waitFor();
  await otherPage.getByText('Замеры и фото прогресса', { exact: true }).waitFor();
  await checkWidth(otherPage, 'member mobile profile');
  await otherContext.close();
  console.log(JSON.stringify({ passed: true, checks: ['owner-only reset', 'six mandatory commitments', 'required purpose', '120 dates', 'single editable Codex source', 'mobile add opens a step in the steps tab', 'immediate offline save and reload', 'cloud retry', 'live earned result', 'midnight auto-close', 'locked previous day', 'idempotent points', 'no repeated reset', 'step creation and focus', 'repeated executions with frozen points', 'steps statistics and reload', 'same account on another device', 'member account isolated', 'mobile and desktop overflow', 'no page errors', 'no sync write loop'], screenshots: output }, null, 2));
} finally {
  await browser.close();
}
