import { Award, CheckCircle2, Crown, Sparkles, Target, Trophy } from 'lucide-react';
import { active, calculateCharacter, skillLevel } from '../life/model';
import { formatShortDate } from '../marathon/model';

export default function AchievementsModule({ marathon, history = [], life, steps }) {
  if (!life) return <div className="grid min-h-64 place-items-center font-black text-slate-500">Собираю итоги…</div>;
  const character = calculateCharacter(life, marathon, steps);
  const skills = life.skills.filter(active).filter((skill) => skillLevel(skill) > 0).sort((a, b) => skillLevel(b) - skillLevel(a));
  const wishes = life.wishes.filter((item) => active(item) && item.status === 'fulfilled');
  const plans = (life.plans || []).filter((item) => active(item) && item.status === 'done');
  return <div className="grid gap-4"><section className="overflow-hidden border border-[#dfd6ad] bg-white rounded-lg"><div className="bg-[#102a43] p-5 text-white"><div className="flex items-center gap-2 text-sm font-black uppercase text-[#f2c14e]"><Crown size={19} />Зал пути</div><h1 className="mt-2 text-3xl font-black">То, что уже нельзя отнять</h1><p className="mt-2 max-w-2xl font-semibold text-slate-200">Марафоны, осуществлённые желания и уровни, подтверждённые делом.</p></div><div className="grid grid-cols-2 gap-px bg-[#e1e9ec] sm:grid-cols-4"><Metric label="Уровень" value={character.level} /><Metric label="Опыт" value={`${character.experience} XP`} /><Metric label="Доказательства" value={character.evidences} /><Metric label="Награды" value={character.achievements.filter((item) => item.earned).length} /></div></section><AchievementSection icon={<Trophy />} title="Завершённые марафоны">{history.length ? history.map((item) => <details key={item.journeyId} className="border border-[#dfd6ad] bg-[#fffdf2] p-4 rounded-md"><summary className="cursor-pointer font-black">{item.status} · {item.durationDays} дней</summary><div className="mt-3 grid grid-cols-2 gap-2 text-sm font-bold text-slate-600 sm:grid-cols-4"><span>{formatShortDate(item.startDate)} — {formatShortDate(item.finishDate)}</span><span>Сильных дней: {item.greenDays}</span><span>Возвратов: {item.redDays}</span><span>Шагов: {item.stepsCompleted}</span></div></details>) : <Empty text="Первый завершённый марафон появится здесь навсегда." />}</AchievementSection><div className="grid gap-4 lg:grid-cols-2"><AchievementSection icon={<Sparkles />} title="Осуществлённые желания">{wishes.length ? wishes.map((item) => <Row key={item.id} title={item.title} meta={item.completedDate || 'Осуществлено'} />) : <Empty text="Пока здесь тихо." />}</AchievementSection><AchievementSection icon={<Target />} title="Выполненные планы">{plans.length ? plans.map((item) => <Row key={item.id} title={item.title} meta={`${item.current}/${item.target} ${item.unit}`} />) : <Empty text="Завершённые планы появятся здесь." />}</AchievementSection></div><AchievementSection icon={<Award />} title="Сильнейшие навыки">{skills.length ? <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{skills.slice(0, 12).map((skill) => <Row key={skill.id} title={skill.title} meta={`Уровень ${skillLevel(skill)}`} />)}</div> : <Empty text="Первое доказательство откроет эту витрину." />}</AchievementSection></div>;
}

function AchievementSection({ icon, title, children }) { return <section className="border border-[#d8e3e7] bg-white p-4 rounded-lg"><div className="flex items-center gap-2"><span className="text-[#0d8fb9]">{icon}</span><h2 className="text-xl font-black">{title}</h2></div><div className="mt-3 grid gap-2">{children}</div></section>; }
function Metric({ label, value }) { return <div className="bg-white p-4"><span className="text-xs font-black uppercase text-slate-500">{label}</span><strong className="mt-1 block text-2xl">{value}</strong></div>; }
function Row({ title, meta }) { return <div className="flex items-center gap-3 border border-[#e1e9ec] bg-[#f8fafb] p-3 rounded-md"><CheckCircle2 size={18} className="shrink-0 text-[#16a36a]" /><div className="min-w-0"><strong className="block break-words text-sm">{title}</strong><span className="text-xs font-bold text-slate-500">{meta}</span></div></div>; }
function Empty({ text }) { return <div className="border border-dashed border-[#cfdde2] p-4 text-sm font-bold text-slate-400 rounded-md">{text}</div>; }
