import { useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Award, Check, Compass, Edit3, ImagePlus, Loader2, Plus, Sparkles, Trash2, TrendingUp, X } from 'lucide-react';
import transformationBanner from '../assets/transformation-banner.webp';
import { createId, number, todayKey } from '../marathon/model';
import { active, addLifeEvent, calculateCharacter, progressFor } from './model';
import { uploadLifeImage } from './files';

const TABS = [
  { id: 'vector', label: 'Вектор', icon: Compass },
  { id: 'skills', label: 'Развитие', icon: TrendingUp },
  { id: 'wishes', label: 'Желания', icon: Sparkles },
  { id: 'character', label: 'Персонаж', icon: Award },
];

export default function CourseModule({ user, state, commit, marathon, steps, syncState, error, retry }) {
  const [tab, setTab] = useState('vector');
  const [editor, setEditor] = useState(null);
  const character = useMemo(() => state ? calculateCharacter(state, marathon, steps) : null, [state, marathon, steps]);
  if (!state) return <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#0d8fb9]" /></div>;
  const saveRecord = (collection, draft) => commit((current, now) => {
    const item = { ...draft, id: draft.id || createId(collection.slice(0, -1)), createdAt: draft.createdAt || now, updatedAt: now, deletedAt: null };
    const exists = current[collection].some((entry) => entry.id === item.id);
    return { ...current, [collection]: exists ? current[collection].map((entry) => entry.id === item.id ? item : entry) : [...current[collection], item] };
  });
  const removeRecord = (collection, id) => commit((current, now) => ({ ...current, [collection]: current[collection].map((item) => item.id === id ? { ...item, deletedAt: now, updatedAt: now } : item) }));
  const saveWish = (draft) => commit((current, now) => {
    const item = { ...draft, id: draft.id || createId('wish'), price: number(draft.price), saved: number(draft.saved), conditions: draft.conditions || [], createdAt: draft.createdAt || now, updatedAt: now, deletedAt: null };
    let next = { ...current, wishes: current.wishes.some((wish) => wish.id === item.id) ? current.wishes.map((wish) => wish.id === item.id ? item : wish) : [...current.wishes, item] };
    if (item.status === 'bought' && !current.events.some((event) => event.linked?.type === 'wish' && event.linked.id === item.id && !event.deletedAt)) next = addLifeEvent(next, { date: item.purchaseDate || todayKey(), type: 'purchase', title: `Куплено: ${item.title}`, description: item.purchaseComment || '', imageUrl: item.imageUrl || '', linked: { type: 'wish', id: item.id }, automatic: true }, now);
    return next;
  });
  const toggleWishCondition = (wishId, conditionId) => commit((current, now) => ({
    ...current,
    wishes: current.wishes.map((wish) => wish.id === wishId ? {
      ...wish,
      conditions: (wish.conditions || []).map((condition) => condition.id === conditionId ? { ...condition, done: !condition.done } : condition),
      updatedAt: now,
    } : wish),
  }));
  const addEvidence = ({ skill, level, evidence }) => commit((current, now) => {
    const nextEvidence = { ...evidence, id: createId('evidence'), date: evidence.date || todayKey(), createdAt: now, updatedAt: now };
    const skills = current.skills.map((item) => item.id === skill.id ? { ...item, level: Math.max(item.level, Number(level)), evidences: [...(item.evidences || []), nextEvidence], updatedAt: now } : item);
    let next = { ...current, skills };
    if (Number(level) > Number(skill.level)) next = addLifeEvent(next, { date: nextEvidence.date, type: 'profession', title: `${skill.title}: уровень ${level}`, description: nextEvidence.text, linked: { type: 'skill', id: skill.id }, automatic: true }, now);
    return next;
  });
  return (
    <div className="grid gap-4">
      <section className="overflow-hidden border border-[#d8e3e7] bg-white rounded-lg">
        <div className="relative min-h-[170px] bg-[#dceff3]" style={{ backgroundImage: `url(${transformationBanner})`, backgroundPosition: 'center', backgroundSize: 'cover' }}><div className="absolute inset-0 bg-white/70" /><div className="relative max-w-2xl p-5 sm:p-6"><div className="text-sm font-black text-[#0d7ea5]">Курс</div><h1 className="mt-2 text-3xl font-black">Кем я становлюсь</h1><p className="mt-2 font-semibold leading-7 text-slate-600">Не идеальная жизнь, а накопленные доказательства движения.</p></div></div>
        <div className="grid grid-cols-2 border-t border-[#d8e3e7] sm:grid-cols-4">{TABS.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => setTab(id)} className={`flex min-h-[52px] items-center justify-center gap-2 border-r border-[#e1e9ec] px-2 text-sm font-black last:border-r-0 ${tab === id ? 'bg-[#102a43] text-white' : 'bg-white text-slate-600'}`}><Icon size={17} />{label}</button>)}</div>
      </section>
      {error && <div className="flex items-center justify-between gap-3 border border-amber-200 bg-amber-50 p-3 text-sm font-bold text-amber-900 rounded-md"><span>{error}</span><button type="button" onClick={retry} className="underline">Повторить</button></div>}
      {tab === 'vector' && <VectorView vectors={state.vectors.filter(active)} onAdd={() => setEditor({ type: 'vector', value: {} })} onEdit={(value) => setEditor({ type: 'vector', value })} />}
      {tab === 'skills' && <SkillsView skills={state.skills.filter(active)} onEvidence={(skill) => setEditor({ type: 'evidence', value: { skill } })} onAdd={() => setEditor({ type: 'skill', value: {} })} onEdit={(value) => setEditor({ type: 'skill', value })} />}
      {tab === 'wishes' && <WishesView wishes={state.wishes.filter(active)} onAdd={() => setEditor({ type: 'wish', value: {} })} onEdit={(value) => setEditor({ type: 'wish', value })} onToggleCondition={toggleWishCondition} />}
      {tab === 'character' && <CharacterView character={character} />}
      <div className="text-right text-xs font-bold text-slate-400">{syncState === 'saving' ? 'Сохраняю Курс…' : syncState === 'offline' ? 'Курс на устройстве' : 'Курс сохранён'}</div>
      <AnimatePresence>{editor?.type === 'vector' && <VectorEditor key="vector" user={user} value={editor.value} onSave={(value) => { saveRecord('vectors', value); setEditor(null); }} onDelete={editor.value.id ? () => { removeRecord('vectors', editor.value.id); setEditor(null); } : null} onClose={() => setEditor(null)} />}{editor?.type === 'skill' && <SkillEditor key="skill" value={editor.value} onSave={(value) => { saveRecord('skills', { level: 0, evidences: [], ...value }); setEditor(null); }} onDelete={editor.value.id ? () => { removeRecord('skills', editor.value.id); setEditor(null); } : null} onClose={() => setEditor(null)} />}{editor?.type === 'evidence' && <EvidenceEditor key="evidence" skill={editor.value.skill} onSave={(value) => { addEvidence(value); setEditor(null); }} onClose={() => setEditor(null)} />}{editor?.type === 'wish' && <WishEditor key="wish" user={user} value={editor.value} onSave={(value) => { saveWish(value); setEditor(null); }} onDelete={editor.value.id ? () => { removeRecord('wishes', editor.value.id); setEditor(null); } : null} onClose={() => setEditor(null)} />}</AnimatePresence>
    </div>
  );
}

function VectorView({ vectors, onAdd, onEdit }) {
  return <section><Header title="Главные векторы" text="Текущая точка, цель и ближайшая веха." onAdd={onAdd} /><div className="mt-4 grid gap-3 lg:grid-cols-3">{vectors.map((vector) => { const progress = progressFor(vector); return <article key={vector.id} className="relative min-h-[300px] overflow-hidden border border-[#d8e3e7] bg-white rounded-lg"><div className="h-36 bg-[#dfe9ec]" style={{ backgroundImage: `url(${vector.imageUrl || transformationBanner})`, backgroundPosition: 'center', backgroundSize: 'cover', filter: `saturate(${0.4 + progress / 165})`, opacity: 0.5 + progress / 200 }} /><div className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black uppercase" style={{ color: vector.color }}>{progress}% пути</div><h2 className="mt-1 text-xl font-black">{vector.title}</h2></div><button type="button" onClick={() => onEdit(vector)} className="icon-command h-9 w-9 shrink-0" title="Редактировать"><Edit3 size={16} /></button></div><p className="mt-2 min-h-12 text-sm font-semibold leading-6 text-slate-600">{vector.description}</p><div className="mt-4 flex items-baseline justify-between"><strong className="text-2xl font-black">{Number(vector.current).toLocaleString('ru-RU')} {vector.unit}</strong><span className="text-xs font-bold text-slate-500">цель {Number(vector.target).toLocaleString('ru-RU')}</span></div><Progress value={progress} color={vector.color} /><div className="mt-3 text-xs font-bold text-slate-500">Ближайшая веха: <strong className="text-[#102a43]">{vector.milestone || 'не задана'}</strong></div></div></article>; })}</div></section>;
}

function SkillsView({ skills, onEvidence, onAdd, onEdit }) {
  const groups = Object.groupBy ? Object.groupBy(skills, (skill) => skill.group) : skills.reduce((acc, skill) => ({ ...acc, [skill.group]: [...(acc[skill.group] || []), skill] }), {});
  return <section><Header title="Дерево развития" text="Уровень растёт только вместе с доказательством." onAdd={onAdd} /><div className="mt-4 grid gap-4">{Object.entries(groups).map(([group, items]) => <section key={group} className="border border-[#d8e3e7] bg-white rounded-lg"><div className="border-b border-[#e1e9ec] p-4"><h2 className="text-lg font-black">{group}</h2><p className="mt-1 text-xs font-bold text-slate-500">Средний уровень: {(items.reduce((sum, item) => sum + item.level, 0) / items.length).toFixed(1)}</p></div><div className="grid gap-px bg-[#e1e9ec] sm:grid-cols-2 lg:grid-cols-3">{items.map((skill) => <div key={skill.id} className="bg-white p-3"><div className="flex items-start justify-between gap-2"><button type="button" onClick={() => onEdit(skill)} className="min-w-0 text-left"><strong className="block truncate text-sm">{skill.title}</strong><span className="mt-1 block text-xs font-bold text-slate-500">{skill.evidences?.length || 0} доказательств</span></button><button type="button" onClick={() => onEvidence(skill)} className="icon-command h-9 w-9 shrink-0" title="Добавить доказательство"><Plus size={16} /></button></div><div className="mt-3 flex gap-1">{[1, 2, 3, 4, 5].map((level) => <i key={level} className={`h-2 flex-1 rounded-sm ${skill.level >= level ? 'bg-[#0d8fb9]' : 'bg-[#e1e9ec]'}`} />)}</div><div className="mt-2 text-xs font-black text-[#0d7ea5]">Уровень {skill.level}</div></div>)}</div></section>)}</div></section>;
}

function WishesView({ wishes, onAdd, onEdit, onToggleCondition }) {
  return <section><Header title="Карта желаний" text="Желания с ценой, смыслом и условиями готовности." onAdd={onAdd} /><div className="mt-4 grid gap-3 md:grid-cols-2">{wishes.map((wish) => { const progress = progressFor(wish); const unlocked = (wish.conditions || []).every((item) => item.done); return <article key={wish.id} className="overflow-hidden border border-[#d8e3e7] bg-white rounded-lg"><div className="relative h-52 bg-[#e1e9ec]" style={{ backgroundImage: `url(${wish.imageUrl || transformationBanner})`, backgroundPosition: 'center', backgroundSize: 'cover', filter: `grayscale(${Math.max(0, 1 - progress / 100)})`, opacity: 0.45 + progress / 180 }}><span className={`absolute left-3 top-3 px-2 py-1 text-xs font-black rounded-sm ${unlocked ? 'bg-[#16a36a] text-white' : 'bg-white text-slate-600'}`}>{unlocked ? 'Разблокировано' : 'Есть условия'}</span></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black uppercase text-[#d55784]">{wish.status || 'want'} · {progress}%</div><h2 className="mt-1 text-xl font-black">{wish.title}</h2></div><button type="button" onClick={() => onEdit(wish)} className="icon-command h-9 w-9" title="Редактировать"><Edit3 size={16} /></button></div><p className="mt-2 text-sm font-semibold leading-6 text-slate-600">{wish.why || wish.description}</p>{wish.price > 0 && <><div className="mt-4 flex justify-between text-sm font-black"><span>{Number(wish.saved || 0).toLocaleString('ru-RU')} ₽</span><span className="text-slate-500">{Number(wish.price).toLocaleString('ru-RU')} ₽</span></div><Progress value={progress} color="#d55784" /></>}{wish.conditions?.length > 0 && <div className="mt-4 grid gap-1">{wish.conditions.map((item) => <button type="button" key={item.id} onClick={() => onToggleCondition(wish.id, item.id)} aria-pressed={item.done} className="flex min-h-8 items-center gap-2 text-left text-xs font-bold text-slate-600"><span className={`grid h-5 w-5 shrink-0 place-items-center border rounded-sm ${item.done ? 'border-[#16a36a] bg-[#16a36a] text-white' : 'border-slate-300 bg-white'}`}>{item.done && <Check size={12} />}</span>{item.title}</button>)}</div>}</div></article>; })}{!wishes.length && <Empty text="Добавь первое желание и опиши, зачем оно тебе." />}</div></section>;
}

function CharacterView({ character }) {
  return <section><Header title={`Персонаж · уровень ${character.level}`} text="Характеристики рассчитываются из реальных действий." /><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{character.attributes.map((item) => <div key={item.id} className="border border-[#d8e3e7] bg-white p-4 rounded-lg"><div className="flex items-baseline justify-between"><strong>{item.title}</strong><span className="text-2xl font-black text-[#0d8fb9]">{item.value}</span></div><Progress value={item.value} color="#0d8fb9" /></div>)}</div><section className="mt-5 border border-[#d8e3e7] bg-white p-4 rounded-lg"><div className="flex items-center gap-2"><Award size={18} className="text-[#8b6b16]" /><h2 className="text-lg font-black">Достижения</h2></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">{character.achievements.map((item) => <div key={item.id} className={`min-h-24 border p-3 rounded-md ${item.earned ? 'border-[#dfd6ad] bg-[#fffdf2]' : 'border-[#e1e9ec] bg-[#f5f8f9] text-slate-400'}`}><Award size={18} /><strong className="mt-2 block text-xs leading-5">{item.title}</strong></div>)}</div></section></section>;
}

function Header({ title, text, onAdd }) { return <div className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-black">{title}</h1><p className="mt-1 text-sm font-semibold text-slate-500">{text}</p></div>{onAdd && <button type="button" onClick={onAdd} className="icon-command" title="Добавить"><Plus size={18} /></button>}</div>; }
function Progress({ value, color }) { return <div className="mt-2 h-2 overflow-hidden bg-[#e7edef] rounded-sm"><motion.div className="h-full" animate={{ width: `${value}%` }} style={{ backgroundColor: color }} /></div>; }
function Empty({ text }) { return <div className="border border-dashed border-[#cfdde2] bg-[#f7f9fa] p-6 text-center text-sm font-bold text-slate-400 rounded-lg">{text}</div>; }

function LifeModal({ title, children, onClose }) { return <motion.div role="dialog" aria-modal="true" aria-label={title} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-[#102a43]/45 p-3 backdrop-blur-sm"><motion.section initial={{ y: 16, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 10, opacity: 0 }} className="my-6 w-full max-w-xl border border-[#d8e3e7] bg-white p-4 shadow-2xl rounded-lg"><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-black">{title}</h2><button type="button" onClick={onClose} className="icon-command" title="Закрыть"><X size={20} /></button></div>{children}</motion.section></motion.div>; }
function FormActions({ valid, onSave, onDelete }) { return <div className="flex gap-2"><button type="button" disabled={!valid} onClick={onSave} className="min-h-12 flex-1 bg-[#16a36a] font-black text-white disabled:bg-slate-300 rounded-md">Сохранить</button>{onDelete && <button type="button" onClick={onDelete} className="icon-command danger h-12 w-12" title="Удалить"><Trash2 size={18} /></button>}</div>; }
function Field({ label, children }) { return <label className="form-label">{label}{children}</label>; }

function ImageField({ user, area, value, onChange }) {
  const [uploading, setUploading] = useState(false); const [error, setError] = useState('');
  const upload = async (file) => { if (!file) return; setUploading(true); setError(''); try { onChange(await uploadLifeImage(user.uid, area, file)); } catch (failure) { setError(failure.message === 'image-too-large' ? 'Максимум 8 МБ' : 'Не удалось загрузить фото'); } finally { setUploading(false); } };
  return <div className="grid gap-2"><label className="form-label">Ссылка на изображение<input type="url" value={value || ''} onChange={(event) => { setError(''); onChange(event.target.value); }} placeholder="https://…" className="field-control mt-2" /></label><label className="flex min-h-12 cursor-pointer items-center justify-center gap-2 border border-[#b9dce8] bg-[#edf9fd] font-black text-[#0d6f91] rounded-md">{uploading ? <Loader2 size={17} className="animate-spin" /> : <ImagePlus size={17} />}{value ? 'Заменить файлом' : 'Загрузить файл'}<input type="file" accept="image/*" disabled={uploading} onChange={(event) => upload(event.target.files?.[0])} className="sr-only" /></label>{error && <div className="text-xs font-bold text-rose-600">{error}. Можно вставить ссылку выше.</div>}</div>;
}

function VectorEditor({ user, value, onSave, onDelete, onClose }) {
  const [draft, setDraft] = useState({ title: '', description: '', current: 0, target: 100, unit: '%', milestone: '', imageUrl: '', color: '#0d8fb9', ...value });
  return <LifeModal title={draft.id ? 'Редактировать вектор' : 'Новый вектор'} onClose={onClose}><div className="grid gap-3"><Field label="Название"><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} className="field-control mt-2" autoFocus /></Field><Field label="Конечный результат"><textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} className="field-control mt-2 h-24" /></Field><div className="grid grid-cols-3 gap-2"><Field label="Сейчас"><input type="number" value={draft.current} onChange={(event) => setDraft({ ...draft, current: event.target.value })} className="field-control mt-2" /></Field><Field label="Цель"><input type="number" value={draft.target} onChange={(event) => setDraft({ ...draft, target: event.target.value })} className="field-control mt-2" /></Field><Field label="Единица"><input value={draft.unit} onChange={(event) => setDraft({ ...draft, unit: event.target.value })} className="field-control mt-2" /></Field></div><Field label="Ближайшая веха"><input value={draft.milestone} onChange={(event) => setDraft({ ...draft, milestone: event.target.value })} className="field-control mt-2" /></Field><ImageField user={user} area="vectors" value={draft.imageUrl} onChange={(imageUrl) => setDraft({ ...draft, imageUrl })} /><FormActions valid={draft.title.trim() && number(draft.target) > 0} onSave={() => onSave(draft)} onDelete={onDelete} /></div></LifeModal>;
}

function SkillEditor({ value, onSave, onDelete, onClose }) { const [draft, setDraft] = useState({ title: '', group: 'Мои навыки', groupId: 'custom', ...value }); return <LifeModal title={draft.id ? 'Навык' : 'Новый навык'} onClose={onClose}><div className="grid gap-3"><Field label="Навык"><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} className="field-control mt-2" autoFocus /></Field><Field label="Группа"><input value={draft.group} onChange={(event) => setDraft({ ...draft, group: event.target.value, groupId: draft.groupId || 'custom' })} className="field-control mt-2" /></Field><FormActions valid={draft.title.trim() && draft.group.trim()} onSave={() => onSave(draft)} onDelete={onDelete} /></div></LifeModal>; }

function EvidenceEditor({ skill, onSave, onClose }) { const [level, setLevel] = useState(Math.min(5, skill.level + 1)); const [evidence, setEvidence] = useState({ type: 'case', text: '', link: '', date: todayKey() }); return <LifeModal title={`Доказательство: ${skill.title}`} onClose={onClose}><div className="grid gap-3"><Field label="Новый уровень"><select value={level} onChange={(event) => setLevel(event.target.value)} className="field-control mt-2">{[0, 1, 2, 3, 4, 5].filter((item) => item >= skill.level).map((item) => <option key={item} value={item}>{item}</option>)}</select></Field><Field label="Тип"><select value={evidence.type} onChange={(event) => setEvidence({ ...evidence, type: event.target.value })} className="field-control mt-2"><option value="case">Реальный кейс</option><option value="setup">Настройка</option><option value="meeting">Встреча</option><option value="code">Код</option><option value="test">Тест</option><option value="note">Заметка</option></select></Field><Field label="Что сделано"><textarea value={evidence.text} onChange={(event) => setEvidence({ ...evidence, text: event.target.value })} className="field-control mt-2 h-28" autoFocus /></Field><Field label="Ссылка"><input value={evidence.link} onChange={(event) => setEvidence({ ...evidence, link: event.target.value })} className="field-control mt-2" /></Field><FormActions valid={evidence.text.trim().length >= 3} onSave={() => onSave({ skill, level, evidence })} /></div></LifeModal>; }

function WishEditor({ user, value, onSave, onDelete, onClose }) {
  const [draft, setDraft] = useState({ title: '', category: 'Жизнь', description: '', why: '', price: 0, saved: 0, priority: 2, desiredDate: '', status: 'want', imageUrl: '', conditions: [], purchaseDate: '', purchaseAmount: '', satisfaction: 3, purchaseComment: '', ...value });
  const [conditionsText, setConditionsText] = useState((draft.conditions || []).map((item) => item.title).join('\n'));
  const submit = () => onSave({ ...draft, conditions: conditionsText.split('\n').map((title, index) => ({ id: draft.conditions?.[index]?.id || createId('condition'), title: title.trim(), done: draft.conditions?.[index]?.done || false })).filter((item) => item.title) });
  return <LifeModal title={draft.id ? 'Желание' : 'Новое желание'} onClose={onClose}><div className="grid gap-3"><Field label="Название"><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} className="field-control mt-2" autoFocus /></Field><Field label="Зачем мне это"><textarea value={draft.why} onChange={(event) => setDraft({ ...draft, why: event.target.value })} className="field-control mt-2 h-20" /></Field><div className="grid grid-cols-2 gap-2"><Field label="Цена, ₽"><input type="number" value={draft.price} onChange={(event) => setDraft({ ...draft, price: event.target.value })} className="field-control mt-2" /></Field><Field label="Накоплено, ₽"><input type="number" value={draft.saved} onChange={(event) => setDraft({ ...draft, saved: event.target.value })} className="field-control mt-2" /></Field></div><Field label="Статус"><select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value })} className="field-control mt-2"><option value="want">Хочу</option><option value="thinking">Думаю</option><option value="saving">Коплю</option><option value="ready">Готово к покупке</option><option value="bought">Куплено</option><option value="declined">Отказался</option></select></Field><Field label="Условия разблокировки, по одному в строке"><textarea value={conditionsText} onChange={(event) => setConditionsText(event.target.value)} className="field-control mt-2 h-24" /></Field>{draft.status === 'bought' && <div className="grid gap-2 border-y border-[#e1e9ec] py-3"><div className="grid grid-cols-2 gap-2"><Field label="Дата покупки"><input type="date" value={draft.purchaseDate || todayKey()} onChange={(event) => setDraft({ ...draft, purchaseDate: event.target.value })} className="field-control mt-2" /></Field><Field label="Фактическая сумма"><input type="number" value={draft.purchaseAmount} onChange={(event) => setDraft({ ...draft, purchaseAmount: event.target.value })} className="field-control mt-2" /></Field></div><Field label={`Удовлетворённость: ${draft.satisfaction}/5`}><input type="range" min="1" max="5" value={draft.satisfaction} onChange={(event) => setDraft({ ...draft, satisfaction: event.target.value })} className="mt-2 w-full" /></Field><Field label="Комментарий"><textarea value={draft.purchaseComment} onChange={(event) => setDraft({ ...draft, purchaseComment: event.target.value })} className="field-control mt-2 h-20" /></Field></div>}<ImageField user={user} area="wishes" value={draft.imageUrl} onChange={(imageUrl) => setDraft({ ...draft, imageUrl })} /><FormActions valid={draft.title.trim()} onSave={submit} onDelete={onDelete} /></div></LifeModal>;
}
